Repository Kernel360/KFE3-bootup-2DooGoBoJa, pull requests merged in 2025-06, with the labels that each got.

#2 [Add] Readme 작성
  README.md
Labels: ➕ Add

#6 [Add] - README 작성
  README.md
Labels: ✨Feature

#12 [Add]-리드미 작성
  README.md
Labels: Docs

#15 [Setting] 보일러플레이트 설정
  .gitignore
  .npmrc
  .vscode/settings.json
  apps/frontEnd/.gitignore
  apps/frontEnd/README.md
  apps/frontEnd/app/favicon.ico
  apps/frontEnd/app/globals.css
  apps/frontEnd/app/layout.tsx
  apps/frontEnd/app/page.tsx
  apps/frontEnd/eslint.config.js
  apps/frontEnd/next-env.d.ts
  apps/frontEnd/next.config.ts
  apps/frontEnd/package.json
  apps/frontEnd/postcss.config.js
  apps/frontEnd/public/circles.svg
  apps/frontEnd/public/next.svg
  apps/frontEnd/public/turborepo.svg
  apps/frontEnd/public/vercel.svg
  apps/frontEnd/tsconfig.json
  package.json
  packages/eslint-config/README.md
  packages/eslint-config/base.js
  packages/eslint-config/next.js
  packages/eslint-config/package.json
  packages/eslint-config/react-internal.js
  packages/tailwind-config/package.json
  packages/tailwind-config/postcss.config.js
  packages/tailwind-config/shared-styles.css
  packages/typescript-config/base.json
  packages/typescript-config/nextjs.json
  packages/typescript-config/package.json
  packages/typescript-config/react-library.json
  packages/ui/.storybook/main.ts
  packages/ui/.storybook/preview.ts
  packages/ui/eslint.config.mjs
  packages/ui/package.json
  packages/ui/src/common/Button.stories.tsx
  packages/ui/src/common/Button.tsx
  packages/ui/src/styles.css
  packages/ui/tsconfig.json
  packages/ui/turbo.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: ⚙ Setting

#18 [Setting] Tailwind CSS storybook과 연결 작업 완료
  packages/ui/.storybook/main.ts
  packages/ui/package.json
  packages/ui/src/common/Button.stories.tsx
  packages/ui/src/common/Button.tsx
  packages/ui/tailwind.config.ts
  packages/ui/tsconfig.json
Labels: ⚙ Setting

#19 [Feat] - badge 공통컴포넌트 제작
  .vscode/settings.json
  packages/ui/src/common/Badge.stories.tsx
  packages/ui/src/common/Badge.tsx
  pnpm-lock.yaml
Labels: ✨Feature

#23 [Feat] - Button 공통 컴포넌트 제작
  README.md
  packages/ui/src/common/Button.stories.tsx
  packages/ui/src/common/Button.tsx
Labels: ✨Feature

#27 [Fix] - 스토리북 수정 안 된 부분 적용
  packages/ui/src/common/Button.stories.tsx
Labels: 🐞BugFix

#31 [Setting] 스토리북 테일윈드 적용
  .DS_Store
  .gitignore
  apps/web/button/Button.stories.tsx
  apps/web/button/Button.tsx
  packages/ui/.storybook/main.ts
  packages/ui/.storybook/preview.ts
  packages/ui/eslint.config.mjs
  packages/ui/package.json
  packages/ui/postcss.config.js
  packages/ui/src/Card/Index.stories.tsx
  packages/ui/src/Card/Index.tsx
  packages/ui/src/card.tsx
  packages/ui/src/global.css
  packages/ui/src/gradient.tsx
  packages/ui/src/styles.css
  packages/ui/src/turborepo-logo.tsx
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: ⚙ Setting

#32 글로벌 스타일 추가
  packages/ui/src/global.css
Labels: 🎨 Style

#39 [settings] next.js, .prettierrc 추가
  .prettierignore
  .prettierrc
  apps/docs/app/globals.css
  apps/docs/app/layout.tsx
  apps/docs/app/page.tsx
  apps/docs/eslint.config.js
  apps/docs/next.config.ts
  apps/docs/vitest.config.ts
  apps/docs/vitest.shims.d.ts
  apps/web/app/globals.css
  apps/web/app/layout.tsx
  apps/web/app/page.tsx
  apps/web/eslint.config.js
  apps/web/next.config.ts
  apps/web/postcss.config.js
  package.json
  packages/eslint-config/base.js
  packages/eslint-config/next.js
  packages/eslint-config/package.json
  packages/eslint-config/react-internal.js
  packages/tailwind-config/postcss.config.js
  packages/ui/.storybook/main.ts
  packages/ui/src/Card/Index.tsx
  pnpm-lock.yaml
Labels: ⚙ Setting

#49 feat: Badge 컴포넌트 개선 & 스토리 수정 (#40)
  packages/ui/src/design-system/base-components/Badge/Badge.stories.tsx
  packages/ui/src/design-system/base-components/Badge/Badge.tsx
  packages/ui/src/design-system/base-components/Badge/index.ts
Labels: ✍️ Refactor
